### ISSUE TITLE
java.lang.IllegalStateException: showAndWait is not allowed during animation or layout processing

### ISSUE THREAD

**Issue by agowa** [ptrckbnck/SQLChecker#10] opened 2019-02-02 20:12 UTC
```
java.lang.IllegalStateException: showAndWait is not allowed during animation or layout processing
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:332)
	at de.unifrankfurt.dbis.GUIApp.showError(GUIApp.java:29)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:241)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.animation.Timeline.doPlayTo(Timeline.java:177)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:99)
	at javafx.animation.Animation.doTimePulse(Animation.java:1101)
	at javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:186)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:515)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Steps to reproduce:
Load the following sqlt file:
```
/*submission_name*/
Blatt4

/*1a*/
/* Kommentar zu Aufgabe 1a
ueber mehrere Zeilen */
...
/*1b*/
-- Kommentar zu Aufgabe 1b
...
/*2a*/
-- Kommentar zu Aufgabe 1c
...
/*2b*/
-- Kommentar 
...
/*2c*/
-- Kommentar 
...
/*2d*/
-- Kommentar 
...
```
Copy following sql statement into 1b:
```
/*1b*/
/* Works with MariaDB 10.3, use union all to stuff two selects together without generating two output tables */
CREATE VIEW eddf_lira_24 AS
SELECT
    ICAO_Code_Origin,
    via,
    Umsteigezeit,
    DepartureDateAndTimeUTC,
    Dauer
FROM
    (
        (
            SELECT
                src.ICAO_Code_Origin,
                "DIREKTFLUG" AS via,
                NULL AS ICAO_Code_Destination,
                src.DepartureDateAndTimeUTC,
                "0" AS Umsteigezeit,
                TIMESTAMPDIFF(MINUTE,DepartureDateAndTimeUTC,ArivalDateAndTimeUTC) AS Dauer
            FROM
                (
                    SELECT
                        *,
                        TIMESTAMPADD(MINUTE,FlightDurationInMinutes,DepartureDateAndTimeUTC) AS ArivalDateAndTimeUTC
                    FROM flightexecution
                ) AS src
            WHERE
                (
                    src.ICAO_Code_Origin = "EDDF" AND
                    src.ICAO_Code_Destination = "LIRA"
                )
        )
    UNION ALL
        (
            SELECT
                src.ICAO_Code_Origin AS ICAO_Code_Origin,
                dst.ICAO_Code_Origin AS via,
                dst.ICAO_Code_Destination,
                src.DepartureDateAndTimeUTC AS DepartureDateAndTimeUTC,
                TIMESTAMPDIFF(MINUTE,src.ArivalDateAndTimeUTC,dst.DepartureDateAndTimeUTC) AS Umsteigezeit,
                TIMESTAMPDIFF(MINUTE,src.DepartureDateAndTimeUTC,dst.ArivalDateAndTimeUTC) AS Dauer
            FROM
                (
                    SELECT
                        *,
                        TIMESTAMPADD(MINUTE,FlightDurationInMinutes,DepartureDateAndTimeUTC) AS ArivalDateAndTimeUTC
                    FROM flightexecution
                ) AS src
            INNER JOIN
                (
                    SELECT
                        *,
                        TIMESTAMPADD(MINUTE,FlightDurationInMinutes,DepartureDateAndTimeUTC) AS ArivalDateAndTimeUTC
                    FROM flightexecution
                ) AS dst ON
                src.ICAO_Code_Destination = dst.ICAO_Code_Origin AND
                TIMESTAMPDIFF(MICROSECOND,src.ArivalDateAndTimeUTC,dst.DepartureDateAndTimeUTC) > 0
            WHERE
                (
                    src.ICAO_Code_Origin = "EDDF" AND
                    dst.ICAO_Code_Destination = "LIRA"
                )
        )
    ) AS a
ORDER BY Dauer;
```
and the error is displayed.

And yes, I know, that this SQL-Statement is:
a) imperformant as hell
b) for some reason only works on newer versions of mariadb
c) look ugly
But it meets the requirements of only one statement per task and works. If it looks stupid but it works it ain't stupid, right?

**Comment by ptrckbnck** [comment] 2019-02-03 11:11
Duplicate of #9

**Closed as completed by ptrckbnck** 2019-02-03 11:11 UTC
Labels: duplicate

**Comment by ptrckbnck** [comment] 2019-02-03 11:13
If your SQL-Statement works, that is all you need. The error has nothing to do with your code. There is a bug with the parsing of the statement for code-highlighting.
You should be able to create the olat-file without problem. So, just ignore the error for now.  
If there are problems with the creation of the olat-file, let me know!
